work with photogallery on add_sight_screen
verhneudinec/surf-flutter-course-kotelnikov pull request #25
Opened 2021-02-16 12:36 UTC by verhneudinec

2021-02-17 11:21 UTC, artem-zaitsev requested changes
Исправьте и ответьте на комментарии.

Про ресурсы касется всех подобных кусков кода

2021-02-17 11:21 UTC, artem-zaitsev commented on lib/models/add_sight.dart
> +  List get sightPhotogallery => _sightPhotogallery;
Избегайте отсутствия типизации у коллекций.

2021-02-17 11:21 UTC, artem-zaitsev commented on lib/ui/screen/add_sight_screen.dart
> +    bool _isFieldsFilled = context.watch<AddSight>().isFieldsFilled;
Такие вещи лучше делать не в build. 
Переместите в didChangeDependencies

2021-02-17 11:21 UTC, artem-zaitsev commented on lib/ui/screen/add_sight_screen.dart
> +    bool _isFieldsFilled = context.watch<AddSight>().isFieldsFilled;
И подумайте чем грозит подписка на значение в build()

2021-02-17 11:21 UTC, artem-zaitsev commented on lib/ui/screen/add_sight_screen.dart
> +                "assets/icons/View.svg",
ресурсы лучше в один файл собрать

2021-02-17 11:21 UTC, artem-zaitsev commented on lib/ui/screen/add_sight_screen.dart
> +                  focusNode: context.watch<AddSight>().longitideFieldFocusNode,
Почему именно watch?

2021-02-17 16:41 UTC, verhneudinec commented on lib/ui/screen/add_sight_screen.dart
> +                  focusNode: context.watch<AddSight>().longitideFieldFocusNode,
Я пока не дошел до 13 раздела. 
Watch использовал по примеру из [документации по провайдеру](https://pub.dev/packages/provider/example),

2021-02-17 17:29 UTC, verhneudinec commented on lib/ui/screen/add_sight_screen.dart
> +    bool _isFieldsFilled = context.watch<AddSight>().isFieldsFilled;
Подскажите, про didChangeDependencies будет в 13-м разделе?

2021-02-17 18:06 UTC, verhneudinec commented on lib/models/add_sight.dart
> +  List get sightPhotogallery => _sightPhotogallery;
[Исправлено](https://github.com/verhneudinec/surf-flutter-course-kotelnikov/pull/28/commits/30cdf960e047a369b76060b092836137bbf7c3e9), учту на будущее

2021-02-17 18:27 UTC, verhneudinec commented on lib/ui/screen/add_sight_screen.dart
> +                "assets/icons/View.svg",
Сделано для всего проекта: [коммит](https://github.com/verhneudinec/surf-flutter-course-kotelnikov/pull/28/commits/0519bf3dd81928be0bc22c315ffdc2ecc49775c5)

2021-02-18 13:14 UTC, artem-zaitsev commented on lib/ui/screen/add_sight_screen.dart
> +                  focusNode: context.watch<AddSight>().longitideFieldFocusNode,
окей, на данном этапе принято. Но смотрите на это аккуратно, так как как раз из-за этого watch иногда опасен.

2021-02-18 13:15 UTC, artem-zaitsev commented on lib/ui/screen/add_sight_screen.dart
> +    bool _isFieldsFilled = context.watch<AddSight>().isFieldsFilled;
Это метод ЖЦ стейта - про него уже была речь. 
Но да, я немного забежал вперед с провайдером. В целом имейте ввиду что подписка в билде на изменения - крайне опасная вещь.

2021-02-20 04:58 UTC, merged