9.2.2. Configuring the data layer
verhneudinec/surf-flutter-course-kotelnikov pull request #47
Opened 2021-03-11 04:37 UTC by verhneudinec

2021-03-15 19:26 UTC, artem-zaitsev requested changes
НЕобходимы правки и проверка, по комментариям

2021-03-15 19:26 UTC, artem-zaitsev commented on lib/data/interactor/sights.dart
> +  final List _sights = mocks;
Почему используется List<dynamic> ?

2021-03-15 19:26 UTC, artem-zaitsev commented on lib/data/models/sights.dart
> +class Sights with ChangeNotifier {
Кажется, у вас два одинаковых файла

2021-03-16 12:30 UTC, verhneudinec commented on lib/data/interactor/sights.dart
> +  final List _sights = mocks;
Артем, типизировал все в 3-м задании

2021-03-16 12:30 UTC, verhneudinec commented on lib/data/models/sights.dart
> +class Sights with ChangeNotifier {
Удалил в следующем ПР :)

2021-03-17 17:52 UTC, merged