13.5: Test work with MobX
verhneudinec/surf-flutter-course-kotelnikov pull request #57
Opened 2021-03-23 05:12 UTC by verhneudinec

2021-03-23 16:50 UTC, artem-zaitsev requested changes

2021-03-23 16:50 UTC, artem-zaitsev commented on lib/ui/screen/places_list_screen.dart
> +    _placesStore = context.watch<PlacesStore>();
тут точно нужен watch?

2021-03-23 16:50 UTC, artem-zaitsev commented on lib/ui/screen/places_list_screen.dart
> +    await context.read<PlacesStore>().loadPlaces();
и тут де read того же

2021-03-23 16:50 UTC, artem-zaitsev commented on lib/ui/screen/places_list_screen.dart
> +    _initStore();
ох, при каждом билде делать запрос - это прям очень затратно и плохо. Первая же точка, котороя бьет по перфомансу.

2021-03-23 16:50 UTC, artem-zaitsev commented on lib/ui/screen/places_list_screen.dart
> +    _initStore();
Вам скорее надо грузить где-то в didChangeDependencies.

2021-03-23 17:37 UTC, verhneudinec commented
BloC сюда случайно попал, не переключил ветку.

Исправления в коммите выше.

Заменил watch на read - можно им обойтись.

Гружу стору в didChangeDependencies.

2021-03-23 17:39 UTC, verhneudinec commented on lib/ui/screen/places_list_screen.dart
> +    await context.read<PlacesStore>().loadPlaces();
Тут сначала сначала сама стора инициализируется и делается на нее подписка, а потом уже грузятся места внутри нее (loadPlaces ничего не возвращает)

2021-03-23 17:44 UTC, verhneudinec commented
Опять же из-за смены веток потерялись изменения, которые я делал в build(). Удалил  _initStore() из билда

2021-03-24 17:43 UTC, artem-zaitsev commented
ок

2021-03-24 19:33 UTC, merged