13.11: MWWM
verhneudinec/surf-flutter-course-kotelnikov pull request #61
Opened 2021-03-25 18:04 UTC by verhneudinec

2021-03-26 16:23 UTC, verhneudinec commented on lib/ui/screen/add_place_screen/add_place_screen.dart
> +        setState(() {});
Почему-то без этого setState не отрабатывает controller.value.text.isNotEmpty

2021-03-26 16:24 UTC, verhneudinec commented on lib/ui/screen/add_place_screen/add_place_screen.dart
>            child: controller.value.text.isNotEmpty
в этом месте. при этом при нажатии hot reload или с setState все работает отлично

2021-03-26 18:02 UTC, artem-zaitsev requested changes
Пока прям оч грязно.
Надо причесать код и немного доразобраться.

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_screen.dart
> +    bool isFieldsFilled = wm.isFieldsFilled.value;
не, лучше реагировать на изменение чего-то через stream builder в данном случае. 
Вы не должны получать значение императивно

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_screen.dart
>              print("Не все поля заполнены"); // TODO Shake bar
Это все должно было переехать в вм

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_screen.dart
>        child: TextButton(
Весь BTextButton надо было завернуть в стрим билдер для реакции на изменение isFilled

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_screen.dart
> +        setState(() {});
Все просто: вы же не подписались на изменение. Вы кладете в стрим новое значение, но при этом не инициируете пересборку. А сет стейт инициирует.

Вам надо обернуть все в подписку на isFilled

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_screen.dart
>            child: controller.value.text.isNotEmpty
Вы просто не подписаны на изменение

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_screen.dart
> +          _photogallery(wm.placePhotogallery),
через StreamBuilder

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +  List<String> placePhotogallery = [];
У вас не должно быть полей, получаемых императивно. Если начинаете использовать реактивность, то лучше соблюдать единообразие в коде. Иначе смотрится грязновато

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +  final addPlaceState = EntityStreamedState<Place>();
Вроде есть отдельный блок для стейтов ниже, почему этот написан здесь?

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +class AddPlaceWidgetModel extends WidgetModel {
Вообще я бы не стал нарушать структуру файла описаную в гайдах Effective Dart. 
Там вроде начинается с полей и заканчивается методами. Сейчас все немного в куче, хотя Вы и попытаплись структурировать

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +      isFieldsFilled.accept(true);
почему бы всю проверку сразу не кинуть в accept?

2021-03-26 18:02 UTC, r3tam commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +      isFieldsFilled.accept(true);
это же бул

2021-03-26 18:02 UTC, artem-zaitsev commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +      return data;
И куда это возвращается? Вы даже не используете возвращаемый тип.
Вообще, у вас тут как будто сразу два варианта подписок и это прям начинает путать

2021-03-26 18:02 UTC, artem-zaitsev commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +  void _clearTextValue(TextEditingController controller) {
а  зачем это все и почему бы сразу не дернуть контроллер? Зачем вы передаете его на юай и потом обратно в вм?

2021-03-26 18:02 UTC, artem-zaitsev commented on pubspec.yaml
> +  mwwm: ^0.1.1
лучше дев версии

2021-03-28 09:45 UTC, verhneudinec commented on lib/ui/screen/add_place_screen/add_place_screen.dart
>              print("Не все поля заполнены"); // TODO Shake bar
Убрал пока эту конструкцию вообще, т.к. о заполненности полей и возможности создания места сигнализирует кнопка "Создать"

2021-03-28 09:45 UTC, verhneudinec commented on lib/ui/screen/add_place_screen/add_place_screen.dart
>            child: controller.value.text.isNotEmpty
Спасибо!

2021-03-28 09:45 UTC, verhneudinec commented on lib/ui/screen/add_place_screen/add_place_screen.dart
> +        setState(() {});
Спасибо!

2021-03-28 15:10 UTC, verhneudinec commented
Исправления будут ниже:

2021-03-29 15:44 UTC, verhneudinec commented on lib/ui/screen/add_place_screen/add_place_screen.dart
> +          _photogallery(wm.placePhotogallery),
Сделано

2021-03-29 15:44 UTC, verhneudinec commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +  void _clearTextValue(TextEditingController controller) {
Действительно:) исправлено

2021-03-29 15:46 UTC, verhneudinec commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +class AddPlaceWidgetModel extends WidgetModel {
Артем, структуру исправил

2021-03-29 17:57 UTC, artem-zaitsev approved these changes
Стало конечно лучше, но прям иногда очень перегружено. Взгляните на свой код так, как если бы вы его увидели впервые через 6 месяцев - все было бы читаемо и понятно?

2021-03-29 17:57 UTC, artem-zaitsev commented on lib/ui/screen/add_place_screen/add_place_screen.dart
> +      child: StreamBuilder<bool>(
Я скорее имел ввиду StreamedStateBuilder (вроде relation то же используете)

2021-03-29 17:57 UTC, artem-zaitsev commented on lib/ui/screen/add_place_screen/add_place_screen.dart
> +          child: StreamBuilder<String>(
лучше использовать StreamedStateBuilder

2021-03-29 17:57 UTC, artem-zaitsev commented on lib/ui/screen/add_place_screen/add_place_screen.dart
>      void _addPlacePhoto() {
Задача на подумать: как это перенести в WM

2021-03-29 17:57 UTC, artem-zaitsev commented on pubspec.yaml
>    relation: ^0.0.2
эту тоже лучше dev

2021-03-29 17:57 UTC, artem-zaitsev commented on lib/ui/screen/add_place_screen/add_place_wm.dart
> +      List<String>.from(placePhotogallery.stateSubject.value.data)
для копирования списка удобнее просто использовать .toList() у любого списка

2021-03-30 06:54 UTC, verhneudinec commented on lib/ui/screen/add_place_screen/add_place_screen.dart
> +      child: StreamBuilder<bool>(
okay!

2021-03-30 06:54 UTC, merged