15.1: Shared preferences
verhneudinec/surf-flutter-course-kotelnikov pull request #67
Opened 2021-04-07 13:31 UTC by verhneudinec

2021-04-08 17:14 UTC, artem-zaitsev requested changes
Ответьте на вопросы или сделайте правки

2021-04-08 17:14 UTC, artem-zaitsev commented on lib/data/repository/storage/app_preferences.dart
> +  static Future setSearchRadius(int value) =>
Future<void> или просто void. Эти мелочи очень сильно бросаются в глаза ревьюерам.

2021-04-08 17:14 UTC, artem-zaitsev commented on lib/data/repository/storage/app_preferences.dart
> +  static Future<int> get searchRadius =>
А почему все static? Вообще, лучше делать экземпляры классов. И передавать их. В данном случае это будет класс который вы создадите единожды и передадите по дереву с помощью того же провайдера.

2021-04-08 17:14 UTC, artem-zaitsev commented on lib/data/repository/storage/preferences_helper.dart
> +class PreferencesHelper {
тот же момент про статик. Если найдете аргументы "за" - озвучьте)

2021-04-08 17:14 UTC, artem-zaitsev commented on lib/main.dart
> +      // onGenerateRoute: (routeSettings) {
почему нет пояснения к комментарию?

2021-04-08 17:42 UTC, verhneudinec commented on lib/data/repository/storage/app_preferences.dart
> +  static Future setSearchRadius(int value) =>
В разработке следующее задание, Артем, не могу переключиться на старую ветку, поэтому просто отвечу здесь.

Проглядел, действительно, типы исправлю на Future<void>, Future<int> и т.д.

2021-04-08 17:45 UTC, verhneudinec commented on lib/main.dart
> +      // onGenerateRoute: (routeSettings) {
эта закомментированная часть кода нужна для дебага: во время конченых тестов я показывал SplashScreen, а при разработке постоянно PlaceListScreenRoute отрабатывал. Это, конечно, убирается в реальных проектах:)

2021-04-08 17:48 UTC, verhneudinec commented on lib/data/repository/storage/app_preferences.dart
> +  static Future<int> get searchRadius =>
Немного дурная причина, но статик использую из-за прямого доступа + доступа без скобок: AppPreferences.searchRadius

Пока полей не сильно много, описать каждый не составляет труда

2021-04-09 05:18 UTC, verhneudinec commented
Добавлены правки выше

2021-04-11 12:59 UTC, merged